### ISSUE TITLE
Error with sound module

### ISSUE THREAD

**Issue by Svenito** [greshake/i3status-rust#26]
With the sound module present I get a panic. Possibly realted to #20

Using latest master: d06583b3f9

config.json:
```
[                                                                               
  {"block": "disk_space", "path": "/", "alias": "/", "type": "available", "unit": "GB", "interval": 20},
  {"block": "memory", "type":"memory", "format_mem":"{Mup}%", "format_swap":"{SUp}%"},
  {"block": "cpu", "interval": 1},                                              
  {"block": "load", "interval": 1, "format": "{1m}"},                           
  {"block": "sound"},                                                           
  {"block": "music", "player": "clementine", "buttons": ["play", "next"]},      
  {"block": "time", "interval": 60, "format": "%a %d/%m %R"}                    
]    
```
Amixer output:
```
amixer get Master
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 64
  Mono: Playback 41 [64%] [-23.00dB] [on]
```
System info:
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Rust Trace:
```
{"version": 1, "click_events": true}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <i3status_rs::blocks::sound::Sound as i3status_rs::block::Block>::update
  11: i3status_rs::main
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:56
  14: __libc_start_main
  15: _start
```

**Comment by greshake** [comment]
Thanks, should be fixed in https://github.com/greshake/i3status-rust/commit/6833c47315bd4e05307d90d4b52e9a250feb059b

**Comment by Svenito** [comment]
Works fine. Thanks!
