### ISSUE TITLE
Panic when focused_window block cannot connect to IPC

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#536]
To reproduce run at a tty without sway/i3 running. Note: this sounds contrived but I actually ran into this issue during an active sway session where the IPC somehow went down.

[This line](https://github.com/greshake/i3status-rust/blob/f6a583682e8ca9b75aa9dc6deb397744432d17c0/src/blocks/focused_window.rs#L54) is the culprit. Need to check before spawning the thread that the IPC is connectable, or need to rewrite the code inside the thread to propagate errors up so we can use `block_error` after `join`ing the thread.

Backtrace:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x564b0fcd8ce4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c5e39dd6bf38933
   1:     0x564b0fcfbc8c - core::fmt::write::h94b22f3cbda6422c
   2:     0x564b0fcd59a7 - std::io::Write::write_fmt::he7e02466cb3dc860
   3:     0x564b0fcdb38e - std::panicking::default_hook::{{closure}}::h077f2d0f0f4550db
   4:     0x564b0fcdb081 - std::panicking::default_hook::hcc1ceebfaf9d0a58
   5:     0x564b0fcdba8b - std::panicking::rust_panic_with_hook::h328d8e7ed959397b
   6:     0x564b0fcdb62e - std::panicking::continue_panic_fmt::h745b12464b662c8f
   7:     0x564b0fcdb516 - rust_begin_unwind
   8:     0x564b0fcf7ace - core::panicking::panic_fmt::hdb91b8826feb6fc9
   9:     0x564b0fcf7bc7 - core::result::unwrap_failed::haba3c6d5a6de1991
  10:     0x564b0f5038d0 - core::result::Result<T,E>::unwrap::h3f1d35fa24952f3d
                               at /build/rust/src/rustc-1.40.0-src/src/libcore/result.rs:933
  11:     0x564b0f75dd87 - <i3status_rs::blocks::focused_window::FocusedWindow as i3status_rs::blocks::ConfigBlock>::new::{{closure}}::hca064e0f0147e248
                               at src/blocks/focused_window.rs:54
  12:     0x564b0f7a6000 - std::sys_common::backtrace::__rust_begin_short_backtrace::h49fe9e8f6df29001
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/sys_common/backtrace.rs:129
  13:     0x564b0f6c97d2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hbcaf183d72c49056
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/thread/mod.rs:469
  14:     0x564b0f69c822 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h861413b3c039f0f8
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/panic.rs:317
  15:     0x564b0f56e4dc - std::panicking::try::do_call::hf8e4ef7e39c8ba81
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/panicking.rs:287
  16:     0x564b0fce37ba - __rust_maybe_catch_panic
  17:     0x564b0f56cc7e - std::panicking::try::h94b234fb9e84ef30
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/panicking.rs:265
  18:     0x564b0f69cb42 - std::panic::catch_unwind::h7bd6e96b94b73647
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/panic.rs:396
  19:     0x564b0f6c6ace - std::thread::Builder::spawn_unchecked::{{closure}}::h2c494a8806a81a27
                               at /build/rust/src/rustc-1.40.0-src/src/libstd/thread/mod.rs:468
  20:     0x564b0f53bdd3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb00a27c0d6380e5b
                               at /build/rust/src/rustc-1.40.0-src/src/libcore/ops/function.rs:227
  21:     0x564b0fcce13f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9c0116b07c5d124e
  22:     0x564b0fce2c60 - std::sys::unix::thread::Thread::new::thread_start::h20a61bfd6b1bfdd0
  23:     0x7f867d61e4cf - start_thread
  24:     0x7f867d5312d3 - clone
  25:                0x0 - <unknown>


Internal error in context 'scheduler': schedule is empty

```

**Comment by atheriel** [comment]
`.unwrap()` strikes again...
