### ISSUE TITLE
i3status-rust panicked in sway while keepassxc closed

### ISSUE THREAD

**Issue by Crandel** [greshake/i3status-rust#777]
I use sway version 1.4 and i3status-rust from latest master. After I close [keepassxc](https://keepassxc.org/) my bar completely gone and I need to reload sway.
My status.toml is [here](https://github.com/Crandel/home/blob/master/.config/sway/status.toml)

I'm starting i3status-rs like this
```
status_command env RUST_BACKTRACE=full i3status-rs --exit-on-error $HOME/.config/sway/status.toml 2>> ~/.local/log/i3status.log
```

error message
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:878:9
stack backtrace:
   0:     0x564e79ede575 - backtrace::backtrace::libunwind::trace::h396c07d2071b43af
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x564e79ede575 - backtrace::backtrace::trace_unsynchronized::h7aa0e4bb23d9c158
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x564e79ede575 - std::sys_common::backtrace::_print_fmt::hd15ac5d4adcd355b
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x564e79ede575 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec5354be8ccc3ecc
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x564e79f0a05c - core::fmt::write::h3d34909eeb4f225b
                               at src/libcore/fmt/mod.rs:1076
   5:     0x564e79eda3d3 - std::io::Write::write_fmt::h1da287b3de55ed16
                               at src/libstd/io/mod.rs:1537
   6:     0x564e79ee0de0 - std::sys_common::backtrace::_print::h4d206838e1ace354
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x564e79ee0de0 - std::sys_common::backtrace::print::h1f778e9940ee5977
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x564e79ee0de0 - std::panicking::default_hook::{{closure}}::h704403a56cbf5783
                               at src/libstd/panicking.rs:198
   9:     0x564e79ee0b2c - std::panicking::default_hook::ha4567a10dec4ef8d
                               at src/libstd/panicking.rs:218
  10:     0x564e79ee1417 - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:486
  11:     0x564e79ee101b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x564e79ee0f8b - std::panicking::begin_panic_fmt::ha3ac96e620978458
                               at src/libstd/panicking.rs:342
  13:     0x564e79ed8e5f - std::io::stdio::print_to::h35adc9bbc938323d
                               at src/libstd/io/stdio.rs:878
  14:     0x564e79ed8e5f - std::io::stdio::_print::h879c358b4105da73
                               at src/libstd/io/stdio.rs:890
  15:     0x564e79c4fbef - i3status_rs::util::print_blocks::h892eaf9580b9d549
  16:     0x564e79ce8360 - i3status_rs::run::h54bc8b8fc2976ef9
  17:     0x564e79ce4806 - i3status_rs::main::h18ae401eaabeced4
  18:     0x564e79ca32e3 - std::rt::lang_start::{{closure}}::hc6b1bfe1d1e11cca
  19:     0x564e79ee18a8 - std::rt::lang_start_internal::{{closure}}::h6d21eebfa4beaf70
                               at src/libstd/rt.rs:52
  20:     0x564e79ee18a8 - std::panicking::try::do_call::h560a27b87db38b9c
                               at src/libstd/panicking.rs:297
  21:     0x564e79ee18a8 - std::panicking::try::h453d4afd696011f9
                               at src/libstd/panicking.rs:274
  22:     0x564e79ee18a8 - std::panic::catch_unwind::h211d02671f23030f
                               at src/libstd/panic.rs:394
  23:     0x564e79ee18a8 - std::rt::lang_start_internal::h464df2bbf46c7e7c
                               at src/libstd/rt.rs:51
  24:     0x564e79ce99c2 - main
  25:     0x7f7c26ae5002 - __libc_start_main
  26:     0x564e79b4019e - _start
  27:                0x0 - <unknown>
thread 'input' panicked at 'cannot access stdin during shutdown', src/libstd/io/stdio.rs:292:25
```

**Comment by ammgws** [comment]
Are you sure you're not just seeing that because of sway crashing first and closing the pipe i3status-rust was writing to?

**Comment by Crandel** [comment]
@ammgws I don't know exactly,  but everything else works fine, except bar, it just gone
