### ISSUE TITLE
Nvidia Block Panic: ParseIntError(InvalidDigit)

### ISSUE THREAD

**Issue by timlyo** [greshake/i3status-rust#803]
I've had a few crashes recently, the cause seems to be a panic in the Nvidia Gpu block. It happens after it's been running for a few minutes.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/blocks/nvidia_gpu.rs:293:30
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: <i3status_rs::blocks::nvidia_gpu::NvidiaGpu as i3status_rs::blocks::Block>::update
  15: i3status_rs::scheduler::UpdateScheduler::do_scheduled_updates
  16: i3status_rs::run
  17: i3status_rs::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  21: std::panicking::try
             at src/libstd/panicking.rs:274
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start

```

**Comment by ammgws** [comment]
It must be getting some funky value for the fan speed that is tripping it up. The code used for that part (`result[count].parse::<u64>().unwrap()`)is the same as for the temperature. What does your block config look like? If you don't already have it enabled, could you add `show_temperature` and see if it changes where the Panic occurs?

**Comment by timlyo** [comment]
My block looks like this

```toml
[[block]]
block = "nvidia_gpu"
label = "GPU"
show_temperature = true
show_memory = false
show_fan_speed = true
interval = 1
```

I've also added a `dbg!()` around the statement I'll let you know if I get anything.

**Comment by ammgws** [comment]
That would be great!

**Comment by ammgws** [comment]
Can you do that for `result_str` and `result` as well? In case there's some weird output there.

**Comment by timlyo** [comment]
Took a while to crash this time, but I've got this out of it:

```
[src/blocks/nvidia_gpu.rs:262] String::from_utf8(output).unwrap() = "4, 54, [Unknown Error]"
[src/blocks/nvidia_gpu.rs:265] result_str.split(", ").collect() = [
    "4",
    "54",
    "[Unknown Error]",
]
[src/blocks/nvidia_gpu.rs:293] count = 2
[src/blocks/nvidia_gpu.rs:293] result[dbg!(count)].parse::<u64>() = Err(
    ParseIntError {
        kind: InvalidDigit,
    },
)
```

**Comment by ammgws** [comment]
Well that third entry is pretty suspect (Unknown Error). It's meant the be the fan speed value.

Can you run `nvidia-smi -i 0 --query-gpu=utilization.gpu,temperature.gpu,fan.speed, --format=csv,noheader,nounits` in a terminal and see what the output looks like? And/or try dbg! on `output` (L251)

**Comment by timlyo** [comment]
The output from the command is what you'd expect (`0, 45, 0`) and `output` is the same as that. I've change the line to `unwrap_or(0)` for now to stop mine crashing, but I'm not sure what the best way of handling this would be.

**Comment by ammgws** [comment]
Did you run the command in a loop for a little while? I'd expect "Unknown Error" to pop up at some time

**Comment by ammgws** [comment]
> I've change the line to `unwrap_or(0)` for now to stop mine crashing, but I'm not sure what the best way of handling this would be.

Let's just go with this for now.
